// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxqXkx6yKxSncA6lW5x9qf2rMdnUobDdk',
    appId: '1:930073181539:web:47a6cf97e8d22d03ea2756',
    messagingSenderId: '930073181539',
    projectId: 'barcode-1922b',
    authDomain: 'barcode-1922b.firebaseapp.com',
    storageBucket: 'barcode-1922b.appspot.com',
    measurementId: 'G-NY5H2LDYT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPixz2EUH23EmR7sF4UTz9VmPA5ADJEyU',
    appId: '1:930073181539:android:027cdc74ae561807ea2756',
    messagingSenderId: '930073181539',
    projectId: 'barcode-1922b',
    storageBucket: 'barcode-1922b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADPNH_qfaGXjoACinDqfXMt1M3wRfe3Wc',
    appId: '1:930073181539:ios:0b2f2fabe9674a1dea2756',
    messagingSenderId: '930073181539',
    projectId: 'barcode-1922b',
    storageBucket: 'barcode-1922b.appspot.com',
    iosBundleId: 'com.example.barcode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADPNH_qfaGXjoACinDqfXMt1M3wRfe3Wc',
    appId: '1:930073181539:ios:0b2f2fabe9674a1dea2756',
    messagingSenderId: '930073181539',
    projectId: 'barcode-1922b',
    storageBucket: 'barcode-1922b.appspot.com',
    iosBundleId: 'com.example.barcode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxqXkx6yKxSncA6lW5x9qf2rMdnUobDdk',
    appId: '1:930073181539:web:64d44c7d106d5b07ea2756',
    messagingSenderId: '930073181539',
    projectId: 'barcode-1922b',
    authDomain: 'barcode-1922b.firebaseapp.com',
    storageBucket: 'barcode-1922b.appspot.com',
    measurementId: 'G-JZPW6X43V9',
  );
}
